### ISSUE TITLE
How do you use this on the command line?

### ISSUE THREAD

**Issue by Stokestack** [fabrv/mustache.ts#1]
Hi. I'm new to Deno. I'm following [a Mustache tutorial](https://www.tsmean.com/articles/mustache/the-ultimate-mustache-tutorial/) and prefer to use Deno instead of installing Node.

I used the same syntax as provided for mustache.js, but I don't get any output from mustache.ts. I tried:

`deno run https://deno.land/x/mustache_ts/mustache.ts friends.json letter-template.mustache > letter.txt`

But the resulting file is always empty. I did get it working in TypeScript, however.

Any help appreciated!

**Comment by fabrv** [comment]
Hello, this is only a library it has no CLI
